# Mostro pubkey, it can be hex or npub
mostro_pubkey = "mostro_pubkey_hex_format"
# Admin private key - leave empty for user mode
admin_privkey=""
# Relays to connect to
relays = ["wss://relay.mostro.network"]
log_level = "info"
currencies = ["VES", "ARS", "USD"]
nsec_privkey='nsec1_privkey_format'
user_mode = "user"
pow = 0