# Mostro pubkey, it can be hex or npub
mostro_pubkey = "82fa8cb978b43c79b2156585bac2c011176a21d2aead6d9f7c575c005be88390"
# Admin private key - leave empty for user mode
admin_privkey=""
# Relays to connect to
relays = ["wss://relay.mostro.network","wss://damus.realy.io"]
log_level = "info"
currencies = ["VES", "ARS", "USD"]
nsec_privkey='nsec1zpmjgd00jckr90zpa0wjhjldgrwy0p6cg3m2m4qcqh5fsx3c786q3c5ksu'
pow = 0